name: CI

on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: Install system dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -y install libasound2-dev

    - name: Install nodejs dependencies
      run: npm ci && npm run bootstrap

    - name: Build TS
      run: npm run build
